---
- name: Deploy application in new kubernetes newspace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: ~/.kube/config
    - name: Deploy nginx application
      kubernetes.core.k8s:
        src: ~/ansible-projects/ansible-eks/nginx-kubernetes.yaml
        state: present
        kubeconfig: ~/.kube/config
        namespace: my-app